# Generated by Django 5.1.5 on 2025-05-17 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start",
            field=models.DateTimeField(),
        ),
    ]
